### ISSUE TITLE
Issue with DataLoader returning 0 length

### ISSUE THREAD

**Issue by CodeWZT** [sanmin0312/LabelDistill#2]
Description: Hi, I encountered an issue when running the code from this repository. It seems that the DataLoader is returning 0 length, which causes the training process to halt with a warning message. Here are the details:
```
| Name  | Type         | Params
---------------------------------------
0 | model | LabelEncoder | 40.0 M
---------------------------------------
31.1 M    Trainable params
8.9 M     Non-trainable params
40.0 M    Total params
80.048    Total estimated model params size (MB)
/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:96: UserWarning: `DataLoader` returned 0 length. Please make sure this was your intention.
  rank_zero_warn(
/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:127: UserWarning: Total length of `CombinedLoader` across ranks is zero. Please make sure this was your intention.
  rank_zero_warn(
/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1938: PossibleUserWarning: The number of training samples (0) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Training: 0it [00:00, ?it/s]
```
Additional Issue with gen_depth_gt.py
After setting up the environment and dependencies exactly as specified in the repository, I encountered another issue with the gen_depth_gt.py script. It appears that the script doesn’t produce any output, and it seems to be skipped during execution. There’s no error message, and it does not generate the expected depth ground truth files.

Steps Taken
Confirmed that all dependencies are installed as per the configuration.
Checked the environment setup and reinstalled necessary packages to ensure compatibility.
Verified that the paths and dataset setup align with the repository’s instructions.
Despite following the instructions, the issues with DataLoader returning 0 samples and gen_depth_gt.py not working persist.

Could you provide guidance on additional configurations or potential fixes? Any advice or troubleshooting steps would be greatly appreciated.

Thank you in advance for your assistance!

**Comment by sanmin0312** [comment]
Regarding your first issue with the DataLoader returning zero samples, it appears this might be related to the second issue with gen_depth_gt.py. The generated depth_gt data is essential for the code to run correctly.

For the gen_depth_gt.py script, it may seem unresponsive initially, as it takes around 20 minutes to generate the depth_gt. There won’t be any visible output until the process completes. However, shortly after you run the script, a [depth_gt] directory should be created in ./data/nuScenes. I’ve re-checked, and it’s functioning as expected on my end.

Additionally, I noticed a minor typo in gen_info.py, which I’ve corrected in this [commit](https://github.com/sanmin0312/LabelDistill/commit/274ab26dc168a02a01436c146a10dd463073afe3). While this typo may not directly cause the issues you're experiencing, I recommend pulling the latest changes and re-running gen_info.py before running gen_depth_gt.py.

**Comment by CodeWZT** [comment]
I have modified the code according to your suggestion and successfully generated the depth_gt file. However, the issue with the DataLoader returning a length of 0 still persists, and the following warning messages continue to appear during training:

/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:96: UserWarning: DataLoader returned 0 length.
/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:127: UserWarning: Total length of CombinedLoader across ranks is zero.
/mnt/data/zhoutao.wang/anaconda3/envs/labeldistill/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1938: PossibleUserWarning: The number of training samples (0) is smaller than the logging interval Trainer(log_every_n_steps=50).

**Comment by CodeWZT** [comment]
Thank for your suggestion, now, I can run the code.
